"""empty message

Revision ID: 0fa6edd80fdb
Revises: 49ef90c08d0a
Create Date: 2022-11-01 00:23:15.391555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa6edd80fdb'
down_revision = '49ef90c08d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planets', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='foreignkey')
    op.drop_column('planets', 'person_id')
    # ### end Alembic commands ###
